FROM python:3.10-slim

ARG BOT_NAME
ARG GAME_PORT=50051
ARG BOT_PORT

WORKDIR /app
COPY ./ ./
COPY ./examples/randbot.py ./main.py

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE ${BOT_PORT}

CMD python3 ./main.py --bn=${BOT_NAME} --la=${BOT_NAME}:${BOT_PORT} --gs=game:${GAME_PORT}
