# Build the Go binary
FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY . ./
RUN go mod download && \
  CGO_ENABLED=0 GOOS=linux go build -o game cmd/main.go

FROM alpine:3.20.3
WORKDIR /app
COPY . ./
COPY --from=builder /app/game ./
EXPOSE 50051
# Command to run the Go binary
CMD ["./game"]
